travis:
  secure:
    BINSTAR_TOKEN: bHO3m6vCfAYlEgrR6Ab1aZqZs1ztxQiFqybPjzp8ohW2Owbh1hp1Gcu4yTjhwWHxmxpEDdHcS8TtgvjUMSMNHx8j0Dt9YMwxFFIwbI+rVKxBqrvv2eTKqGdgzYvAv8Mo1UmvqCyiPPFVg+IxFHv3ZhrELNIjlCeszeMynfkdbXbAah8d1lRfG3Jlpm3Mlep68vOULu6S0ptqdMGR0voSCworATvstwzXX4JCJzTAxpJbCSQMamazTTdnVgoeoKYzM2aD39D4SzdhS/9NQBSNq0I0Ssoc91bylB8HDxR4xqIa6o5KRtcKjWxKaBlEawD+RQt4oHuYxYMqGLE+rtpnRyESayO6RkNIUDjZnqaWU9og2hiRVNyShjf41Pl5c/ot8S5z5hLqd5M2ygLzoZmtgpqvHLZUqlsgpeZPySF/ZGppvgGhZK+kBfnWiz1NZWH4Xz2VjZSv/94BzboXTXmbjMAPzoxmGDomq9JL2oNNqttu3xiS1trZMUXfSLbekK3gzpQy9tbNpY5unu9GVgC+7kjiuYejDUFYvEaROPfY1QSdpJVv4NzydMPqHs518eawD1JJF/m3eVb9bQ+WAhkORMom4AJ3eDVpPStxZGHo5X1o6QuLRn4kXVfXpuJyqo8i+aMHT5//W3Ay5v0gBHtbwvQiAl/7iG+oxQXGYsBJEK4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
